-- Appeals + claim adjudication (P1-PR4). Guarded — no synthea schema in CI.
--
-- claim_adjudication: the decision on a claim line, as its own fact with its
--   own date (Synthea's encounters stay untouched). One encounter = one
--   claim line (stated simplification).
-- appeals: one row per case, tied to ONE denied claim line and to the call
--   in which the member disputed the denial (an appeal is a downstream
--   process reading upstream records — generated by an additive pass over
--   the merged call log, never by regenerating the storylines).
-- appeal_evidence: what each case cites (call note, clinical note, policy,
--   determination letter). Nothing reads it yet: Phase 2's relational
--   entitlement (a clinical note is visible to the appeals tier only while
--   an appeal cites it) enforces over this table.
DO $$
BEGIN
    IF to_regclass('synthea.patients') IS NOT NULL THEN
        CREATE TABLE IF NOT EXISTS synthea.claim_adjudication (
            encounter     text PRIMARY KEY REFERENCES synthea.encounters (id),
            claim_id      text NOT NULL,  -- 9-digit space: a handful of encounters share a number (one claim, two lines)
            patient       text NOT NULL REFERENCES synthea.patients (id),
            member_id     text NOT NULL,
            status        text NOT NULL CHECK (status IN ('paid', 'denied', 'pending')),
            decision_date date,
            denial_reason text,
            policy_id     text
        );
        CREATE INDEX IF NOT EXISTS claim_adjudication_patient_idx ON synthea.claim_adjudication (patient);
        CREATE INDEX IF NOT EXISTS claim_adjudication_claim_idx ON synthea.claim_adjudication (claim_id);
        CREATE TABLE IF NOT EXISTS synthea.appeals (
            case_id       text PRIMARY KEY,
            patient       text NOT NULL REFERENCES synthea.patients (id),
            member_id     text NOT NULL,
            encounter     text NOT NULL REFERENCES synthea.claim_adjudication (encounter),
            claim_id      text NOT NULL,
            call_id       text REFERENCES synthea.call_log (call_id),
            filed_date    date NOT NULL,
            appeal_type   text NOT NULL CHECK (appeal_type IN ('pre_service', 'post_service', 'grievance')),
            denial_reason text NOT NULL,
            decision      text NOT NULL CHECK (decision IN ('upheld', 'overturned', 'partially_overturned', 'pending')),
            decided_date  date,
            reviewer      text,
            policy_id     text
        );
        CREATE INDEX IF NOT EXISTS appeals_patient_idx ON synthea.appeals (patient);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS appeal_evidence (
    case_id        text NOT NULL,
    document_title text NOT NULL,  -- documents.title of the cited document (or a policy id, ahead of P1-PR6)
    kind           text NOT NULL,  -- call_note | clinical_note | clinical_policy | determination_letter
    PRIMARY KEY (case_id, document_title)
);
CREATE INDEX IF NOT EXISTS appeal_evidence_document_idx ON appeal_evidence (document_title);

-- Appeal documents go live under the provisional employee tier (Phase 2
-- creates the appeals tier and re-tags). Records about one member, dated
-- by filing: member-scoped and event, like call notes. Chunked by section;
-- every chunk carries the case row's fields as metadata (record context),
-- so a case or claim id in a question is a filter, not a search word.
UPDATE sources SET acl_tag = 'employee', status = 'ingested', member_scoped = true, event = true
WHERE key = 'appeal_documents';
UPDATE sources SET status = 'loaded' WHERE key IN ('appeals', 'claim_adjudication');
-- Its own BM25 statistics (migration 010's rule: each new vector source adds its index).
CREATE INDEX IF NOT EXISTS chunks_bm25_appeal_idx ON chunks USING bm25 (index_text) WITH (text_config = 'english') WHERE doc_type = 'appeal';
