-- Lane 2 governance: Synthea claims under Snowflake row access policies +
-- dynamic masking. Fully idempotent — a lapsed trial is recreated by
-- re-running `raglab snowflake-setup`. Requires Enterprise edition (the
-- masking-policy DDL fails loudly on Standard).
--
-- Access model (workforce minimum-necessary, all internal roles):
--   CLAIMS_EXAMINER  full claim detail (identity + clinical + financial)
--   PSHB_EXAMINER    same detail, row-scoped to the PSHB book of business
--   CARE_MANAGER     clinical context; financial columns masked to NULL
--   ACTUARY          de-identified rows: names -> stable hashes (joinable),
--                    SSN -> NULL, birthdate -> year only; clinical +
--                    financial intact for aggregation
-- Enforced by the warehouse, not app code: same SELECT, four result shapes.

CREATE WAREHOUSE IF NOT EXISTS RAGLAB_WH
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RAGLAB_WH;
CREATE DATABASE IF NOT EXISTS RAGLAB;
CREATE SCHEMA IF NOT EXISTS RAGLAB.CLAIMS;
USE SCHEMA RAGLAB.CLAIMS;

CREATE ROLE IF NOT EXISTS CLAIMS_EXAMINER;
CREATE ROLE IF NOT EXISTS PSHB_EXAMINER;
CREATE ROLE IF NOT EXISTS CARE_MANAGER;
CREATE ROLE IF NOT EXISTS ACTUARY;

CREATE OR REPLACE TABLE PATIENTS (
    ID               STRING,
    MEMBER_ID        STRING,              -- natural key (raglab identifiers)
    MRN              STRING,
    BIRTHDATE        DATE,
    SSN              STRING,
    FIRST_NAME       STRING,
    LAST_NAME        STRING,
    GENDER           STRING,
    RACE             STRING,
    ETHNICITY        STRING,
    CITY             STRING,
    STATE            STRING,
    ZIP              STRING,
    LINE_OF_BUSINESS STRING
);

-- One row per member per plan year (from synthea.enrollment).
CREATE OR REPLACE TABLE ENROLLMENT (
    PATIENT_ID       STRING,
    MEMBER_ID        STRING,
    YEAR             NUMBER,
    LINE_OF_BUSINESS STRING,
    PLAN_CODE        STRING,
    PLAN_OPTION      STRING,
    TIER             STRING,
    ENROLLMENT_CODE  STRING
);

-- Call-center interaction records (fields only; note text lives in the
-- vector lane). No financial columns; member identifiers masked for the actuary.
CREATE OR REPLACE TABLE CALL_LOG (
    CALL_ID          STRING,
    PATIENT_ID       STRING,
    MEMBER_ID        STRING,
    CALL_DATE        DATE,
    REP_ID           STRING,
    REASON_CODE      STRING,
    DISPOSITION      STRING,
    CLAIM_ID         STRING,
    DURATION_SEC     NUMBER,
    LINE_OF_BUSINESS STRING
);

CREATE OR REPLACE TABLE CLAIM_LINES (
    ID               STRING,
    PATIENT_ID       STRING,
    SERVICE_DATE     DATE,
    ENCOUNTER_CLASS  STRING,
    CODE             STRING,
    DESCRIPTION      STRING,
    REASON           STRING,
    BASE_COST        NUMBER(12,2),
    TOTAL_CLAIM_COST NUMBER(12,2),
    PAYER_COVERAGE   NUMBER(12,2),
    LINE_OF_BUSINESS STRING
);

-- Role -> book-of-business scope, consulted by the row access policy.
-- Owner-only: personas never read the mapping, they only feel it.
CREATE OR REPLACE TABLE LOB_ENTITLEMENTS (ROLE_NAME STRING, LOB STRING);
INSERT INTO LOB_ENTITLEMENTS VALUES
    ('ACCOUNTADMIN', 'FEHB'), ('ACCOUNTADMIN', 'PSHB'),
    ('CLAIMS_EXAMINER', 'FEHB'), ('CLAIMS_EXAMINER', 'PSHB'),
    ('CARE_MANAGER', 'FEHB'), ('CARE_MANAGER', 'PSHB'),
    ('ACTUARY', 'FEHB'), ('ACTUARY', 'PSHB'),
    ('PSHB_EXAMINER', 'PSHB');

-- Dynamic masking: identity columns blank out for the ACTUARY; financial
-- columns blank out for the CARE_MANAGER. Everyone else sees through.
CREATE OR REPLACE MASKING POLICY MASK_NAME AS (VAL STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('ACTUARY') THEN SHA2(VAL, 256) ELSE VAL END;

CREATE OR REPLACE MASKING POLICY MASK_SSN AS (VAL STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('ACTUARY') THEN NULL ELSE VAL END;

-- Member identifiers are masked for the actuary exactly like the SSN.
CREATE OR REPLACE MASKING POLICY MASK_IDENTIFIER AS (VAL STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('ACTUARY') THEN NULL ELSE VAL END;

CREATE OR REPLACE MASKING POLICY MASK_BIRTHDATE AS (VAL DATE) RETURNS DATE ->
    CASE WHEN IS_ROLE_IN_SESSION('ACTUARY')
         THEN DATE_FROM_PARTS(YEAR(VAL), 1, 1) ELSE VAL END;

CREATE OR REPLACE MASKING POLICY MASK_FINANCIAL AS (VAL NUMBER) RETURNS NUMBER ->
    CASE WHEN IS_ROLE_IN_SESSION('CARE_MANAGER') THEN NULL ELSE VAL END;

ALTER TABLE PATIENTS MODIFY COLUMN FIRST_NAME SET MASKING POLICY MASK_NAME;
ALTER TABLE PATIENTS MODIFY COLUMN LAST_NAME  SET MASKING POLICY MASK_NAME;
ALTER TABLE PATIENTS MODIFY COLUMN SSN        SET MASKING POLICY MASK_SSN;
ALTER TABLE PATIENTS MODIFY COLUMN MEMBER_ID  SET MASKING POLICY MASK_IDENTIFIER;
ALTER TABLE PATIENTS MODIFY COLUMN MRN        SET MASKING POLICY MASK_IDENTIFIER;
ALTER TABLE ENROLLMENT MODIFY COLUMN MEMBER_ID SET MASKING POLICY MASK_IDENTIFIER;
ALTER TABLE CALL_LOG   MODIFY COLUMN MEMBER_ID SET MASKING POLICY MASK_IDENTIFIER;
ALTER TABLE CALL_LOG   MODIFY COLUMN CLAIM_ID  SET MASKING POLICY MASK_IDENTIFIER;
ALTER TABLE PATIENTS MODIFY COLUMN BIRTHDATE  SET MASKING POLICY MASK_BIRTHDATE;
ALTER TABLE CLAIM_LINES MODIFY COLUMN BASE_COST        SET MASKING POLICY MASK_FINANCIAL;
ALTER TABLE CLAIM_LINES MODIFY COLUMN TOTAL_CLAIM_COST SET MASKING POLICY MASK_FINANCIAL;
ALTER TABLE CLAIM_LINES MODIFY COLUMN PAYER_COVERAGE   SET MASKING POLICY MASK_FINANCIAL;

-- Row access: a role sees only the books of business it is entitled to.
-- Evaluated with the policy owner's rights, so the mapping table stays
-- invisible to the personas it governs.
CREATE OR REPLACE ROW ACCESS POLICY LOB_SCOPE AS (LOB STRING) RETURNS BOOLEAN ->
    EXISTS (
        SELECT 1 FROM RAGLAB.CLAIMS.LOB_ENTITLEMENTS E
        WHERE E.ROLE_NAME = CURRENT_ROLE() AND E.LOB = LOB
    );

ALTER TABLE PATIENTS    ADD ROW ACCESS POLICY LOB_SCOPE ON (LINE_OF_BUSINESS);
ALTER TABLE CLAIM_LINES ADD ROW ACCESS POLICY LOB_SCOPE ON (LINE_OF_BUSINESS);
ALTER TABLE ENROLLMENT  ADD ROW ACCESS POLICY LOB_SCOPE ON (LINE_OF_BUSINESS);
ALTER TABLE CALL_LOG    ADD ROW ACCESS POLICY LOB_SCOPE ON (LINE_OF_BUSINESS);

-- The demo query surface: one governed join, columns inherit base masking.
CREATE OR REPLACE VIEW CLAIM_DETAIL AS
SELECT
    P.MEMBER_ID, P.FIRST_NAME, P.LAST_NAME, P.SSN, P.BIRTHDATE,
    C.ID AS CLAIM_ID, C.PATIENT_ID, C.SERVICE_DATE, C.ENCOUNTER_CLASS,
    C.DESCRIPTION, C.REASON, C.TOTAL_CLAIM_COST, C.PAYER_COVERAGE,
    C.LINE_OF_BUSINESS
FROM CLAIM_LINES C
JOIN PATIENTS P ON P.ID = C.PATIENT_ID;

CREATE STAGE IF NOT EXISTS LOAD_STAGE
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE);

GRANT USAGE ON WAREHOUSE RAGLAB_WH TO ROLE CLAIMS_EXAMINER;
GRANT USAGE ON WAREHOUSE RAGLAB_WH TO ROLE PSHB_EXAMINER;
GRANT USAGE ON WAREHOUSE RAGLAB_WH TO ROLE CARE_MANAGER;
GRANT USAGE ON WAREHOUSE RAGLAB_WH TO ROLE ACTUARY;
GRANT USAGE ON DATABASE RAGLAB TO ROLE CLAIMS_EXAMINER;
GRANT USAGE ON DATABASE RAGLAB TO ROLE PSHB_EXAMINER;
GRANT USAGE ON DATABASE RAGLAB TO ROLE CARE_MANAGER;
GRANT USAGE ON DATABASE RAGLAB TO ROLE ACTUARY;
GRANT USAGE ON SCHEMA RAGLAB.CLAIMS TO ROLE CLAIMS_EXAMINER;
GRANT USAGE ON SCHEMA RAGLAB.CLAIMS TO ROLE PSHB_EXAMINER;
GRANT USAGE ON SCHEMA RAGLAB.CLAIMS TO ROLE CARE_MANAGER;
GRANT USAGE ON SCHEMA RAGLAB.CLAIMS TO ROLE ACTUARY;
GRANT SELECT ON TABLE PATIENTS TO ROLE CLAIMS_EXAMINER;
GRANT SELECT ON TABLE PATIENTS TO ROLE PSHB_EXAMINER;
GRANT SELECT ON TABLE PATIENTS TO ROLE CARE_MANAGER;
GRANT SELECT ON TABLE PATIENTS TO ROLE ACTUARY;
GRANT SELECT ON TABLE CLAIM_LINES TO ROLE CLAIMS_EXAMINER;
GRANT SELECT ON TABLE CLAIM_LINES TO ROLE PSHB_EXAMINER;
GRANT SELECT ON TABLE CLAIM_LINES TO ROLE CARE_MANAGER;
GRANT SELECT ON TABLE CLAIM_LINES TO ROLE ACTUARY;
GRANT SELECT ON VIEW CLAIM_DETAIL TO ROLE CLAIMS_EXAMINER;
GRANT SELECT ON VIEW CLAIM_DETAIL TO ROLE PSHB_EXAMINER;
GRANT SELECT ON VIEW CLAIM_DETAIL TO ROLE CARE_MANAGER;
GRANT SELECT ON VIEW CLAIM_DETAIL TO ROLE ACTUARY;
GRANT SELECT ON TABLE ENROLLMENT TO ROLE CLAIMS_EXAMINER;
GRANT SELECT ON TABLE ENROLLMENT TO ROLE PSHB_EXAMINER;
GRANT SELECT ON TABLE ENROLLMENT TO ROLE CARE_MANAGER;
GRANT SELECT ON TABLE ENROLLMENT TO ROLE ACTUARY;
GRANT SELECT ON TABLE CALL_LOG TO ROLE CLAIMS_EXAMINER;
GRANT SELECT ON TABLE CALL_LOG TO ROLE PSHB_EXAMINER;
GRANT SELECT ON TABLE CALL_LOG TO ROLE CARE_MANAGER;
GRANT SELECT ON TABLE CALL_LOG TO ROLE ACTUARY;
